name: "Build"

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  BuildWindows:
    runs-on: "windows-2022"

    strategy:
      matrix:
        config:
          - "Release"

    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Run Build-Windows.ps1"
        run: "./Build-Windows.ps1 -Configuration ${{ matrix.config }}"

      - uses: "actions/upload-artifact@v3"
        with:
          name: "onnxruntime-win-${{ matrix.config }}"
          path: "release/onnxruntime-windows-${{ matrix.config }}.zip"

  Release:
    runs-on: "ubuntu-22.04"
    if: "github.event_name == 'push' && contains(github.ref, 'refs/tags/')"
    needs: 
      - "BuildWindows"
    permissions:
      contents: "write"
    steps:
      - name: "Get Metadata"
        id: "metadata"
        run: |
          echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: "Download build artifacts"
        uses: "actions/download-artifact@v3"

      - name: "Create Release"
        uses: "softprops/action-gh-release@v1"
        with:
          draft: true
          tag_name: "${{ steps.metadata.outputs.version }}"
          name: "${{ steps.metadata.outputs.version }}"
          files: |
            ${{ github.workspace }}/**/*.zip
